[workspace]
members = ["xtask", "checkr", "inspectify", "checko"]

[workspace.package]
version = "0.1.5"
repository = "https://github.com/team-checkr/checkr/"
authors = [
    "Oliver Bøving <oliver@bvng.dk>",
    "Camilla Færch <camilla_faerch@hotmail.com>",
]

[workspace.dependencies]
color-eyre = "0.6.2"
itertools = "0.10.5"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["full"] }
tracing = "0.1.37"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
checkr = { path = "./checkr" }
checko = { path = "./checko" }
tsify = "0.4.3"
typeshare = "1.0.0"

[workspace.metadata.release]
publish = false
tag-name = "v{{version}}"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.0.4"
# The preferred Rust toolchain to use in CI (rustup toolchain syntax)
rust-toolchain-version = "1.67.1"
# CI backends to support (see 'cargo dist generate-ci')
ci = ["github"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "aarch64-apple-darwin",
]

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
