[toolchain]
channel = "nightly-2023-01-10"
components = ["rust-src", "rustfmt", "rust-std", "llvm-tools-preview"]
targets = [
    "wasm32-unknown-unknown",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    "aarch64-apple-darwin",
]
