[package]
name = "checko"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.2"
axum-macros = "0.3.1"
clap = { version = "4.0.32", features = ["derive"] }
comfy-table = "6.1.4"
gitlab = "0.1507.0"
indexmap = { version = "1.9.2", features = ["serde"] }
itertools = "0.10.5"
rayon = "1.6.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.24.1", features = ["full", "tracing"] }
toml = { version = "0.7.0", features = ["indexmap"] }
tower = { version = "0.4.13", features = ["tracing"] }
tower-http = { version = "0.3.5", features = [
    "cors",
    "fs",
    "tracing",
    "trace",
] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
url = "2.3.1"
checkr = { version = "0.1.0", path = "../checkr" }
xshell = "0.2.3"
color-eyre = "0.6.2"
tracing-error = "0.2.0"
git-repository = { version = "0.33.0", features = [
    "blocking-http-transport-reqwest",
] }
