[package]
name = "checko"
edition = "2021"
version = { workspace = true }
repository = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
checkr = { workspace = true }
clap = { version = "4.0.32", features = ["derive"] }
color-eyre = { workspace = true }
comfy-table = { workspace = true }
gix = { version = "0.42.0", features = ["blocking-http-transport-reqwest"] }
indexmap = { version = "1.9.2", features = ["serde"] }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
toml = { version = "0.7.0", features = ["indexmap"] }
tracing = { workspace = true }
tracing-error = { workspace = true }
tracing-subscriber = { workspace = true }
url = "2.3.1"
xshell = "0.2.3"
